### ISSUE TITLE
script generates error if no credential file is present - need a better prompt 

### ISSUE THREAD

**Issue by brucenelson6655** [brucenelson6655/serverless-pl-tool#1]
THis is too harsh : serverless-pl/serverlesspl.py -C get_ncc -n e8eccce3-56b3-4919-a852-b8918923e849
Traceback (most recent call last):
  File "serverless-pl/serverlesspl.py", line 688, in <module>
    sys.exit(main())
  File "serverless-pl/serverlesspl.py", line 461, in main
    bearer = get_bearer_token_msal(config_file, login_type)
  File "serverless-pl/serverlesspl.py", line 36, in get_bearer_token_msal
    with open(credfile) as json_data:
FileNotFoundError: [Errno 2] No such file or directory: 'credential.json'

**Comment by brucenelson6655** [comment]
Planning to jump to an interactive mode and build a credential file if one is missing. Same for missing parameters if discovered
